### valid request
POST https://home24-page-analyzer.herokuapp.com/url-analyze
Content-Type: application/json

{
  "url": "http://example.com/"
}

### invalid request with empty url
POST https://home24-page-analyzer.herokuapp.com/url-analyze
Content-Type: application/json

{
  "url": ""
}

### invalid request with no url field
POST https://home24-page-analyzer.herokuapp.com/url-analyze
Content-Type: application/json

{
  "test-url": "https://regex101.com/"
}

### invalid url
POST https://home24-page-analyzer.herokuapp.com/url-analyze
Content-Type: application/json

{
  "url": "https://testing@test.com"
}