### valid request
POST http://localhost:8080/url-analyze
Content-Type: application/json

{
  "url": "https://example.com/"
}

### invalid request with empty url
POST http://localhost:8080/url-analyze
Content-Type: application/json

{
  "url": ""
}

### invalid request with no url field
POST http://localhost:8080/url-analyze
Content-Type: application/json

{
  "test-url": "https://regex101.com/"
}

### invalid url
POST http://localhost:8080/url-analyze
Content-Type: application/json

{
  "url": "https://testing@test.com"
}